apiVersion: v1
kind: Service
metadata:
  name: flask-kube-service
spec:
  selector:
    app: flask_kube
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: flask-kube
   labels:
     app: flask_kube
spec:
  selector:
     matchLabels:
       app: flask_kube
       version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: flask_kube
        version: v1
      spec:
       containers:
       - name: flask_kube
         image: flask_kube:latest
         ports:
          - containerPort: 3000